Added android NemID code
meewworld/flutter_nemid pull request #1
Opened 2020-07-24 11:58 UTC by MichaelWestergaard

2020-07-26 23:37 UTC, AlenDK commented on android/src/main/java/dk/meew/flutter_nemid/communication/ValidationResponse.java
> +}
new line

2020-07-26 23:37 UTC, AlenDK requested changes
Added one comment

2020-07-27 12:21 UTC, SebastianTracey approved these changes
Umiddelbart Approve, men der er meget kode og jeg er ikke inde i det hele så det vil tage laaaaaaaaang tid at lave et ordenligt CR på dette for at få den fulde forståelse 🗡️

2020-07-27 12:21 UTC, SebastianTracey approved these changes
Approved umiddelbart :D

2020-07-27 12:27 UTC, AlenDK approved these changes

2020-07-27 12:36 UTC, merged