Changed plugin to reflect changes in the backend
meewworld/flutter_nemid pull request #3
Opened 2020-10-15 13:20 UTC by MichaelWestergaard

The backend is using prod certificate, so you need to use your real NemID

2020-10-16 11:35 UTC, AlenDK commented on lib/flutter_nemid.dart
> +
delete white space

2020-10-16 11:43 UTC, Swoop86dk approved these changes
Looks good. Approved.

2020-10-16 12:18 UTC, AlenDK approved these changes

2020-10-16 12:42 UTC, SebastianTracey requested changes
Super fint! 

Jeg har lige et par kommenterer og et par spørgsmål hertil - førend jeg approver ;)

2020-10-16 12:42 UTC, SebastianTracey commented on android/src/main/java/dk/meew/flutter_nemid/FlutterNemidPlugin.java
> +        e.printStackTrace();
dette er vel det samme som en print, right? Eller er det "rigtigt" errorhandling? :D

2020-10-16 12:42 UTC, SebastianTracey commented on android/src/main/java/dk/meew/flutter_nemid/MainActivity.java
> +import okhttp3.Call;
add newline - så du holder imports adskilt ligesom i `android/src/main/java/dk/meew/flutter_nemid/FlutterNemidPlugin.java`

2020-10-16 12:42 UTC, SebastianTracey commented on android/src/main/java/dk/meew/flutter_nemid/MainActivity.java
>  import androidx.annotation.NonNull;
add newline ovenfor- så du holder imports adskilt ligesom i `android/src/main/java/dk/meew/flutter_nemid/FlutterNemidPlugin.java`

2020-10-16 12:42 UTC, SebastianTracey commented on android/src/main/java/dk/meew/flutter_nemid/MainActivity.java
> +import androidx.annotation.RequiresApi;
add newline efter denne linje - så du holder imports adskilt ligesom i `android/src/main/java/dk/meew/flutter_nemid/FlutterNemidPlugin.java`

2020-10-16 12:42 UTC, SebastianTracey commented on android/src/main/java/dk/meew/flutter_nemid/MainActivity.java
> +
slet emptyline :D

2020-10-16 12:42 UTC, SebastianTracey commented on android/src/main/java/dk/meew/flutter_nemid/MainActivity.java
> +            e.printStackTrace();
samme spørgsmål som før til denne? :D

2020-10-16 12:42 UTC, SebastianTracey commented on ios/Classes/NetworkUtilities.m
> +
remove empty line :D

2020-10-20 07:30 UTC, SebastianTracey approved these changes
Looks clean :D. 

Jeg har umiddelbart ikke nogen indvendinger til det her andet end det skal merges :P

2020-10-20 11:12 UTC, SebastianTracey commented
@MichaelWestergaard - Skal jeg merge den her?

2020-10-20 11:51 UTC, MichaelWestergaard commented
> @MichaelWestergaard - Skal jeg merge den her?

@SebastianTracey du kan merge den nu

2020-10-20 11:53 UTC, SebastianTracey approved these changes
Approved :D

2020-10-20 11:53 UTC, merged